version: 2

models:
  - name: bridge_inpatient_claim_diagnosis
    description: "Bridge table linking inpatient claims to diagnosis codes with positional context."

    columns:
      - name: fact_claim_key
        tests:
          - not_null
          - relationships:
              to: ref('fact_inpatient_claims')
              field: fact_claim_key

      - name: diagnosis_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_diagnosis')
              field: diagnosis_key
